# Generated by Django 5.2.12 on 2026-04-04 01:44

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('icono', models.CharField(blank=True, max_length=100, verbose_name='Ícono')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre_hotel', models.CharField(max_length=150, verbose_name='Nombre del hotel')),
                ('eslogan', models.CharField(blank=True, max_length=255, verbose_name='Eslogan')),
                ('url_logo', models.URLField(blank=True, verbose_name='URL del logo')),
                ('url_favicon', models.URLField(blank=True, verbose_name='URL del favicon')),
                ('color_primario', models.CharField(blank=True, max_length=20, verbose_name='Color primario')),
                ('color_secundario', models.CharField(blank=True, max_length=20, verbose_name='Color secundario')),
                ('color_acento', models.CharField(blank=True, max_length=20, verbose_name='Color de acento')),
                ('idioma_predeterminado', models.CharField(default='es', max_length=10, verbose_name='Idioma predeterminado')),
                ('meta_titulo', models.CharField(blank=True, max_length=255, verbose_name='Meta título')),
                ('meta_descripcion', models.TextField(blank=True, verbose_name='Meta descripción')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
            },
        ),
        migrations.CreateModel(
            name='EnlaceReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre_plataforma', models.CharField(max_length=100, verbose_name='Nombre de la plataforma')),
                ('tipo_plataforma', models.CharField(choices=[('booking', 'Booking'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('tripadvisor', 'Tripadvisor'), ('whatsapp', 'WhatsApp'), ('phone', 'Teléfono'), ('email', 'Correo'), ('website', 'Sitio web'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de plataforma')),
                ('url', models.URLField(verbose_name='URL')),
                ('url_icono', models.URLField(blank=True, verbose_name='URL del ícono')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('texto_boton', models.CharField(blank=True, max_length=100, verbose_name='Texto del botón')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es principal')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('orden_mostrar', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Enlace de reserva',
                'verbose_name_plural': 'Enlaces de reserva',
                'ordering': ['orden_mostrar', 'nombre_plataforma'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre_huesped', models.CharField(blank=True, max_length=150, verbose_name='Nombre del huésped')),
                ('ubicacion_huesped', models.CharField(blank=True, max_length=150, verbose_name='Ubicación del huésped')),
                ('fuente', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google'), ('booking', 'Booking'), ('airbnb', 'Airbnb'), ('tripadvisor', 'Tripadvisor'), ('direct', 'Directo'), ('other', 'Otro')], default='direct', max_length=20, verbose_name='Fuente')),
                ('etiqueta_fuente', models.CharField(blank=True, max_length=100, verbose_name='Etiqueta de la fuente')),
                ('url_fuente', models.URLField(blank=True, verbose_name='URL de la fuente')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_experiencia', models.DateField(blank=True, null=True, verbose_name='Fecha de la experiencia')),
                ('es_destacada', models.BooleanField(default=False, verbose_name='Es destacada')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('orden_mostrar', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['orden_mostrar', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('descripcion_corta', models.TextField(blank=True, verbose_name='Descripción corta')),
                ('descripcion_completa', models.TextField(blank=True, verbose_name='Descripción completa')),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('tipo_cama', models.CharField(blank=True, max_length=100, verbose_name='Tipo de cama')),
                ('tamano_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tamaño en m²')),
                ('tipo_vista', models.CharField(blank=True, max_length=100, verbose_name='Tipo de vista')),
                ('precio_referencia_currency', djmoney.models.fields.CurrencyField(choices=[('XUA', 'ADB Unit of Account'), ('AFN', 'Afghan Afghani'), ('AFA', 'Afghan Afghani (1927–2002)'), ('ALL', 'Albanian Lek'), ('ALK', 'Albanian Lek (1946–1965)'), ('DZD', 'Algerian Dinar'), ('ADP', 'Andorran Peseta'), ('AOA', 'Angolan Kwanza'), ('AOK', 'Angolan Kwanza (1977–1991)'), ('AON', 'Angolan New Kwanza (1990–2000)'), ('AOR', 'Angolan Readjusted Kwanza (1995–1999)'), ('ARA', 'Argentine Austral'), ('ARS', 'Argentine Peso'), ('ARM', 'Argentine Peso (1881–1970)'), ('ARP', 'Argentine Peso (1983–1985)'), ('ARL', 'Argentine Peso Ley (1970–1983)'), ('AMD', 'Armenian Dram'), ('AWG', 'Aruban Florin'), ('AUD', 'Australian Dollar'), ('ATS', 'Austrian Schilling'), ('AZN', 'Azerbaijani Manat'), ('AZM', 'Azerbaijani Manat (1993–2006)'), ('BSD', 'Bahamian Dollar'), ('BHD', 'Bahraini Dinar'), ('BDT', 'Bangladeshi Taka'), ('BBD', 'Barbadian Dollar'), ('BYN', 'Belarusian Ruble'), ('BYB', 'Belarusian Ruble (1994–1999)'), ('BYR', 'Belarusian Ruble (2000–2016)'), ('BEF', 'Belgian Franc'), ('BEC', 'Belgian Franc (convertible)'), ('BEL', 'Belgian Franc (financial)'), ('BZD', 'Belize Dollar'), ('BMD', 'Bermudan Dollar'), ('BTN', 'Bhutanese Ngultrum'), ('BOB', 'Bolivian Boliviano'), ('BOL', 'Bolivian Boliviano (1863–1963)'), ('BOV', 'Bolivian Mvdol'), ('BOP', 'Bolivian Peso'), ('VED', 'Bolívar Soberano'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BAD', 'Bosnia-Herzegovina Dinar (1992–1994)'), ('BAN', 'Bosnia-Herzegovina New Dinar (1994–1997)'), ('BWP', 'Botswanan Pula'), ('BRC', 'Brazilian Cruzado (1986–1989)'), ('BRZ', 'Brazilian Cruzeiro (1942–1967)'), ('BRE', 'Brazilian Cruzeiro (1990–1993)'), ('BRR', 'Brazilian Cruzeiro (1993–1994)'), ('BRN', 'Brazilian New Cruzado (1989–1990)'), ('BRB', 'Brazilian New Cruzeiro (1967–1986)'), ('BRL', 'Brazilian Real'), ('GBP', 'British Pound'), ('BND', 'Brunei Dollar'), ('BGL', 'Bulgarian Hard Lev'), ('BGN', 'Bulgarian Lev'), ('BGO', 'Bulgarian Lev (1879–1952)'), ('BGM', 'Bulgarian Socialist Lev'), ('BUK', 'Burmese Kyat'), ('BIF', 'Burundian Franc'), ('XPF', 'CFP Franc'), ('KHR', 'Cambodian Riel'), ('CAD', 'Canadian Dollar'), ('CVE', 'Cape Verdean Escudo'), ('KYD', 'Cayman Islands Dollar'), ('XAF', 'Central African CFA Franc'), ('CLE', 'Chilean Escudo'), ('CLP', 'Chilean Peso'), ('CLF', 'Chilean Unit of Account (UF)'), ('CNX', 'Chinese People’s Bank Dollar'), ('CNY', 'Chinese Yuan'), ('CNH', 'Chinese Yuan (offshore)'), ('COP', 'Colombian Peso'), ('COU', 'Colombian Real Value Unit'), ('KMF', 'Comorian Franc'), ('CDF', 'Congolese Franc'), ('CRC', 'Costa Rican Colón'), ('HRD', 'Croatian Dinar'), ('HRK', 'Croatian Kuna'), ('CUC', 'Cuban Convertible Peso'), ('CUP', 'Cuban Peso'), ('CYP', 'Cypriot Pound'), ('CZK', 'Czech Koruna'), ('CSK', 'Czechoslovak Hard Koruna'), ('DKK', 'Danish Krone'), ('DJF', 'Djiboutian Franc'), ('DOP', 'Dominican Peso'), ('NLG', 'Dutch Guilder'), ('XCD', 'East Caribbean Dollar'), ('DDM', 'East German Mark'), ('ECS', 'Ecuadorian Sucre'), ('ECV', 'Ecuadorian Unit of Constant Value'), ('EGP', 'Egyptian Pound'), ('GQE', 'Equatorial Guinean Ekwele'), ('ERN', 'Eritrean Nakfa'), ('EEK', 'Estonian Kroon'), ('ETB', 'Ethiopian Birr'), ('EUR', 'Euro'), ('XBA', 'European Composite Unit'), ('XEU', 'European Currency Unit'), ('XBB', 'European Monetary Unit'), ('XBC', 'European Unit of Account (XBC)'), ('XBD', 'European Unit of Account (XBD)'), ('FKP', 'Falkland Islands Pound'), ('FJD', 'Fijian Dollar'), ('FIM', 'Finnish Markka'), ('FRF', 'French Franc'), ('XFO', 'French Gold Franc'), ('XFU', 'French UIC-Franc'), ('GMD', 'Gambian Dalasi'), ('GEK', 'Georgian Kupon Larit'), ('GEL', 'Georgian Lari'), ('DEM', 'German Mark'), ('GHS', 'Ghanaian Cedi'), ('GHC', 'Ghanaian Cedi (1979–2007)'), ('GIP', 'Gibraltar Pound'), ('XAU', 'Gold'), ('GRD', 'Greek Drachma'), ('GTQ', 'Guatemalan Quetzal'), ('GWP', 'Guinea-Bissau Peso'), ('GNF', 'Guinean Franc'), ('GNS', 'Guinean Syli'), ('GYD', 'Guyanaese Dollar'), ('HTG', 'Haitian Gourde'), ('HNL', 'Honduran Lempira'), ('HKD', 'Hong Kong Dollar'), ('HUF', 'Hungarian Forint'), ('IMP', 'IMP'), ('ISK', 'Icelandic Króna'), ('ISJ', 'Icelandic Króna (1918–1981)'), ('INR', 'Indian Rupee'), ('IDR', 'Indonesian Rupiah'), ('IRR', 'Iranian Rial'), ('IQD', 'Iraqi Dinar'), ('IEP', 'Irish Pound'), ('ILS', 'Israeli New Shekel'), ('ILP', 'Israeli Pound'), ('ILR', 'Israeli Shekel (1980–1985)'), ('ITL', 'Italian Lira'), ('JMD', 'Jamaican Dollar'), ('JPY', 'Japanese Yen'), ('JOD', 'Jordanian Dinar'), ('KZT', 'Kazakhstani Tenge'), ('KES', 'Kenyan Shilling'), ('KWD', 'Kuwaiti Dinar'), ('KGS', 'Kyrgystani Som'), ('LAK', 'Laotian Kip'), ('LVL', 'Latvian Lats'), ('LVR', 'Latvian Ruble'), ('LBP', 'Lebanese Pound'), ('LSL', 'Lesotho Loti'), ('LRD', 'Liberian Dollar'), ('LYD', 'Libyan Dinar'), ('LTL', 'Lithuanian Litas'), ('LTT', 'Lithuanian Talonas'), ('LUL', 'Luxembourg Financial Franc'), ('LUC', 'Luxembourgian Convertible Franc'), ('LUF', 'Luxembourgian Franc'), ('MOP', 'Macanese Pataca'), ('MKD', 'Macedonian Denar'), ('MKN', 'Macedonian Denar (1992–1993)'), ('MGA', 'Malagasy Ariary'), ('MGF', 'Malagasy Franc'), ('MWK', 'Malawian Kwacha'), ('MYR', 'Malaysian Ringgit'), ('MVR', 'Maldivian Rufiyaa'), ('MVP', 'Maldivian Rupee (1947–1981)'), ('MLF', 'Malian Franc'), ('MTL', 'Maltese Lira'), ('MTP', 'Maltese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('MRO', 'Mauritanian Ouguiya (1973–2017)'), ('MUR', 'Mauritian Rupee'), ('MXV', 'Mexican Investment Unit'), ('MXN', 'Mexican Peso'), ('MXP', 'Mexican Silver Peso (1861–1992)'), ('MDC', 'Moldovan Cupon'), ('MDL', 'Moldovan Leu'), ('MCF', 'Monegasque Franc'), ('MNT', 'Mongolian Tugrik'), ('MAD', 'Moroccan Dirham'), ('MAF', 'Moroccan Franc'), ('MZE', 'Mozambican Escudo'), ('MZN', 'Mozambican Metical'), ('MZM', 'Mozambican Metical (1980–2006)'), ('MMK', 'Myanmar Kyat'), ('NAD', 'Namibian Dollar'), ('NPR', 'Nepalese Rupee'), ('ANG', 'Netherlands Antillean Guilder'), ('TWD', 'New Taiwan Dollar'), ('NZD', 'New Zealand Dollar'), ('NIO', 'Nicaraguan Córdoba'), ('NIC', 'Nicaraguan Córdoba (1988–1991)'), ('NGN', 'Nigerian Naira'), ('KPW', 'North Korean Won'), ('NOK', 'Norwegian Krone'), ('OMR', 'Omani Rial'), ('PKR', 'Pakistani Rupee'), ('XPD', 'Palladium'), ('PAB', 'Panamanian Balboa'), ('PGK', 'Papua New Guinean Kina'), ('PYG', 'Paraguayan Guarani'), ('PEI', 'Peruvian Inti'), ('PEN', 'Peruvian Sol'), ('PES', 'Peruvian Sol (1863–1965)'), ('PHP', 'Philippine Peso'), ('XPT', 'Platinum'), ('PLN', 'Polish Zloty'), ('PLZ', 'Polish Zloty (1950–1995)'), ('PTE', 'Portuguese Escudo'), ('GWE', 'Portuguese Guinea Escudo'), ('QAR', 'Qatari Riyal'), ('XRE', 'RINET Funds'), ('RHD', 'Rhodesian Dollar'), ('RON', 'Romanian Leu'), ('ROL', 'Romanian Leu (1952–2006)'), ('RUB', 'Russian Ruble'), ('RUR', 'Russian Ruble (1991–1998)'), ('RWF', 'Rwandan Franc'), ('SVC', 'Salvadoran Colón'), ('WST', 'Samoan Tala'), ('SAR', 'Saudi Riyal'), ('RSD', 'Serbian Dinar'), ('CSD', 'Serbian Dinar (2002–2006)'), ('SCR', 'Seychellois Rupee'), ('SLE', 'Sierra Leonean Leone'), ('SLL', 'Sierra Leonean Leone (1964—2022)'), ('XAG', 'Silver'), ('SGD', 'Singapore Dollar'), ('SKK', 'Slovak Koruna'), ('SIT', 'Slovenian Tolar'), ('SBD', 'Solomon Islands Dollar'), ('SOS', 'Somali Shilling'), ('ZAR', 'South African Rand'), ('ZAL', 'South African Rand (financial)'), ('KRH', 'South Korean Hwan (1953–1962)'), ('KRW', 'South Korean Won'), ('KRO', 'South Korean Won (1945–1953)'), ('SSP', 'South Sudanese Pound'), ('SUR', 'Soviet Rouble'), ('ESP', 'Spanish Peseta'), ('ESA', 'Spanish Peseta (A account)'), ('ESB', 'Spanish Peseta (convertible account)'), ('XDR', 'Special Drawing Rights'), ('LKR', 'Sri Lankan Rupee'), ('SHP', 'St. Helena Pound'), ('XSU', 'Sucre'), ('SDD', 'Sudanese Dinar (1992–2007)'), ('SDG', 'Sudanese Pound'), ('SDP', 'Sudanese Pound (1957–1998)'), ('SRD', 'Surinamese Dollar'), ('SRG', 'Surinamese Guilder'), ('SZL', 'Swazi Lilangeni'), ('SEK', 'Swedish Krona'), ('CHF', 'Swiss Franc'), ('SYP', 'Syrian Pound'), ('STN', 'São Tomé & Príncipe Dobra'), ('STD', 'São Tomé & Príncipe Dobra (1977–2017)'), ('TVD', 'TVD'), ('TJR', 'Tajikistani Ruble'), ('TJS', 'Tajikistani Somoni'), ('TZS', 'Tanzanian Shilling'), ('XTS', 'Testing Currency Code'), ('THB', 'Thai Baht'), ('TPE', 'Timorese Escudo'), ('TOP', 'Tongan Paʻanga'), ('TTD', 'Trinidad & Tobago Dollar'), ('TND', 'Tunisian Dinar'), ('TRY', 'Turkish Lira'), ('TRL', 'Turkish Lira (1922–2005)'), ('TMT', 'Turkmenistani Manat'), ('TMM', 'Turkmenistani Manat (1993–2009)'), ('USD', 'US Dollar'), ('USN', 'US Dollar (Next day)'), ('USS', 'US Dollar (Same day)'), ('UGX', 'Ugandan Shilling'), ('UGS', 'Ugandan Shilling (1966–1987)'), ('UAH', 'Ukrainian Hryvnia'), ('UAK', 'Ukrainian Karbovanets'), ('AED', 'United Arab Emirates Dirham'), ('UYW', 'Uruguayan Nominal Wage Index Unit'), ('UYU', 'Uruguayan Peso'), ('UYP', 'Uruguayan Peso (1975–1993)'), ('UYI', 'Uruguayan Peso (Indexed Units)'), ('UZS', 'Uzbekistani Som'), ('VUV', 'Vanuatu Vatu'), ('VES', 'Venezuelan Bolívar'), ('VEB', 'Venezuelan Bolívar (1871–2008)'), ('VEF', 'Venezuelan Bolívar (2008–2018)'), ('VND', 'Vietnamese Dong'), ('VNN', 'Vietnamese Dong (1978–1985)'), ('CHE', 'WIR Euro'), ('CHW', 'WIR Franc'), ('XOF', 'West African CFA Franc'), ('YDD', 'Yemeni Dinar'), ('YER', 'Yemeni Rial'), ('YUN', 'Yugoslavian Convertible Dinar (1990–1992)'), ('YUD', 'Yugoslavian Hard Dinar (1966–1990)'), ('YUM', 'Yugoslavian New Dinar (1994–2002)'), ('YUR', 'Yugoslavian Reformed Dinar (1992–1993)'), ('ZWN', 'ZWN'), ('ZRN', 'Zairean New Zaire (1993–1998)'), ('ZRZ', 'Zairean Zaire (1971–1993)'), ('ZMW', 'Zambian Kwacha'), ('ZMK', 'Zambian Kwacha (1968–2012)'), ('ZWD', 'Zimbabwean Dollar (1980–2008)'), ('ZWR', 'Zimbabwean Dollar (2008)'), ('ZWL', 'Zimbabwean Dollar (2009–2024)')], default='COL', editable=False, max_length=3, null=True)),
                ('precio_referencia', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='COL', max_digits=10, null=True, verbose_name='Precio de referencia')),
                ('es_destacada', models.BooleanField(default=False, verbose_name='Es destacada')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
                ('orden_mostrar', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['orden_mostrar', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InformacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=150, verbose_name='Barrio')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado_region', models.CharField(blank=True, max_length=100, verbose_name='Estado o región')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('url_google_maps', models.URLField(blank=True, verbose_name='URL de Google Maps')),
                ('hora_check_in', models.TimeField(blank=True, null=True, verbose_name='Hora de check-in')),
                ('hora_check_out', models.TimeField(blank=True, null=True, verbose_name='Hora de check-out')),
                ('url_facebook', models.URLField(blank=True, verbose_name='URL de Facebook')),
                ('url_instagram', models.URLField(blank=True, verbose_name='URL de Instagram')),
                ('url_youtube', models.URLField(blank=True, verbose_name='URL de YouTube')),
                ('url_tiktok', models.URLField(blank=True, verbose_name='URL de TikTok')),
                ('url_x', models.URLField(blank=True, verbose_name='URL de X')),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Información de contacto',
            },
        ),
        migrations.CreateModel(
            name='SeccionAcercaDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('historia', models.TextField(blank=True, verbose_name='Historia')),
                ('mision', models.TextField(blank=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, verbose_name='Visión')),
                ('url_imagen_principal', models.URLField(blank=True, verbose_name='URL de la imagen principal')),
                ('url_imagen_secundaria', models.URLField(blank=True, verbose_name='URL de la imagen secundaria')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'Sección acerca de',
                'verbose_name_plural': 'Secciones acerca de',
            },
        ),
        migrations.CreateModel(
            name='SeccionHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('url_video', models.URLField(blank=True, verbose_name='URL del video')),
                ('url_video_movil', models.URLField(blank=True, verbose_name='URL del video móvil')),
                ('url_poster', models.URLField(blank=True, verbose_name='URL del poster')),
                ('texto_boton_primario', models.CharField(blank=True, max_length=100, verbose_name='Texto del botón primario')),
                ('url_boton_primario', models.CharField(blank=True, max_length=255, verbose_name='URL del botón primario')),
                ('texto_boton_secundario', models.CharField(blank=True, max_length=100, verbose_name='Texto del botón secundario')),
                ('url_boton_secundario', models.CharField(blank=True, max_length=255, verbose_name='URL del botón secundario')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está activo')),
            ],
            options={
                'verbose_name': 'Sección hero',
                'verbose_name_plural': 'Secciones hero',
            },
        ),
        migrations.CreateModel(
            name='HabitacionAmenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.amenidad', verbose_name='Amenidad')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Amenidad de habitación',
                'verbose_name_plural': 'Amenidades de habitaciones',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='amenidades',
            field=models.ManyToManyField(blank=True, related_name='habitaciones', through='contenido.HabitacionAmenidad', to='contenido.amenidad', verbose_name='Amenidades'),
        ),
        migrations.CreateModel(
            name='ImagenExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField(verbose_name='URL de la imagen')),
                ('texto_alternativo', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('orden_mostrar', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='contenido.experiencia', verbose_name='Experiencia')),
            ],
            options={
                'verbose_name': 'Imagen de experiencia',
                'verbose_name_plural': 'Imágenes de experiencias',
                'ordering': ['orden_mostrar', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField(verbose_name='URL de la imagen')),
                ('texto_alternativo', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('es_portada', models.BooleanField(default=False, verbose_name='Es portada')),
                ('orden_mostrar', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='contenido.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Imagen de habitación',
                'verbose_name_plural': 'Imágenes de habitaciones',
                'ordering': ['orden_mostrar', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='habitacionamenidad',
            constraint=models.UniqueConstraint(fields=('habitacion', 'amenidad'), name='unica_habitacion_amenidad'),
        ),
    ]
