"""
Django settings for iraka project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl
load_dotenv()
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
import psycopg2
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contenido.apps.ContenidoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iraka.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iraka.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

DATABASES = {
    'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,
            # ssl_require=True
        ),
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-CO'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Optimización queries django

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "https://iraka-production.up.railway.app",  # sin / al final
    "https://chase-nondrinkable-editorially.ngrok-free.dev",
    "https://iraka.up.railway.app/"
]


UNFOLD = {
    "SITE_TITLE": "Administración Hotel Iraka",
    "SITE_HEADER": "Hotel Iraka",
    "SITE_SUBHEADER": "Gestión de contenido del sitio web",
    "SITE_URL": "/",
    "SITE_SYMBOL": "hotel",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "LOGIN": {
        "image": lambda request: "https://res.cloudinary.com/dnemnrzno/image/upload/v1775270341/logo-iraka_dk0mhw.png",
    },
    "STYLES": [
        lambda request: "css/admin.css",
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Sitio web",
                "separator": True,
                "items": [
                    {
                        "title": "Configuración del sitio",
                        "icon": "settings",
                        "link": "/admin/contenido/configuracionsitio/",
                    },
                    {
                        "title": "Hero",
                        "icon": "slideshow",
                        "link": "/admin/contenido/seccionhero/",
                    },
                    {
                        "title": "Acerca de",
                        "icon": "info",
                        "link": "/admin/contenido/seccionacercade/",
                    },
                    {
                        "title": "Información de contacto",
                        "icon": "call",
                        "link": "/admin/contenido/informacioncontacto/",
                    },
                ],
            },
            {
                "title": "Habitaciones",
                "separator": True,
                "items": [
                    {
                        "title": "Habitaciones",
                        "icon": "bed",
                        "link": "/admin/contenido/habitacion/",
                    },
                    {
                        "title": "Imágenes de habitaciones",
                        "icon": "image",
                        "link": "/admin/contenido/imagenhabitacion/",
                    },
                    {
                        "title": "Amenidades",
                        "icon": "star",
                        "link": "/admin/contenido/amenidad/",
                    },
                    {
                        "title": "Relación habitación-amenidad",
                        "icon": "merge",
                        "link": "/admin/contenido/habitacionamenidad/",
                    },
                ],
            },
            {
                "title": "Experiencias y reservas",
                "separator": True,
                "items": [
                    {
                        "title": "Experiencias",
                        "icon": "forum",
                        "link": "/admin/contenido/experiencia/",
                    },
                    {
                        "title": "Imágenes de experiencias",
                        "icon": "photo_library",
                        "link": "/admin/contenido/imagenexperiencia/",
                    },
                    {
                        "title": "Enlaces de reserva",
                        "icon": "event_available",
                        "link": "/admin/contenido/enlacereserva/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "contenido.configuracionsitio",
                "contenido.seccionhero",
                "contenido.seccionacercade",
                "contenido.informacioncontacto",
            ],
            "items": [
                {
                    "title": "Sitio",
                    "link": "/admin/contenido/configuracionsitio/",
                },
            ],
        },
        {
            "models": [
                "contenido.habitacion",
                "contenido.imagenhabitacion",
                "contenido.amenidad",
                "contenido.habitacionamenidad",
            ],
            "items": [
                {
                    "title": "Habitaciones",
                    "link": "/admin/contenido/habitacion/",
                },
            ],
        },
        {
            "models": [
                "contenido.experiencia",
                "contenido.imagenexperiencia",
                "contenido.enlacereserva",
            ],
            "items": [
                {
                    "title": "Experiencias y reservas",
                    "link": "/admin/contenido/experiencia/",
                },
            ],
        },
    ],
    "COLORS": {
        "base": {
            "50": "oklch(98.6% 0.004 85)",
            "100": "oklch(97.1% 0.006 85)",
            "200": "oklch(93.5% 0.010 82)",
            "300": "oklch(88.3% 0.014 80)",
            "400": "oklch(74.5% 0.018 76)",
            "500": "oklch(59.8% 0.020 72)",
            "600": "oklch(48.2% 0.018 68)",
            "700": "oklch(38.5% 0.016 64)",
            "800": "oklch(29.2% 0.014 58)",
            "900": "oklch(21.8% 0.012 52)",
            "950": "oklch(14.6% 0.010 45)",
        },
        "primary": {
            "50": "oklch(96.8% 0.018 335)",
            "100": "oklch(92.8% 0.038 334)",
            "200": "oklch(86.4% 0.072 332)",
            "300": "oklch(76.5% 0.124 329)",
            "400": "oklch(65.2% 0.178 325)",
            "500": "oklch(54.0% 0.196 321)",
            "600": "oklch(47.2% 0.176 320)",
            "700": "oklch(40.5% 0.152 320)",
            "800": "oklch(33.7% 0.126 321)",
            "900": "oklch(27.8% 0.102 322)",
            "950": "oklch(20.1% 0.075 323)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
}